#!/usr/bin/env python3
"""Generate GB2312 images and build TTF fonts for every prepared style folder."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
if str(Path(__file__).resolve().parent) not in sys.path:
    sys.path.insert(0, str(Path(__file__).resolve().parent))
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from _launcher_utils import maybe_reexec_with_repo_python

maybe_reexec_with_repo_python(__file__, REPO_ROOT)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="One-click export: generate all prepared styles to GB2312 images and build TTFs via potrace + FontForge.",
    )
    parser.add_argument(
        "--checkpoint",
        default="run/lora_ft_large_content_style_encoder/checkpoint-latest.pth",
        help="Finetuned checkpoint used for generation.",
    )
    parser.add_argument(
        "--train-dir",
        default="data/mixed_finetune_dataset/train",
        help="Prepared style-folder directory generated by prepare_mixed_finetune_dataset.py.",
    )
    parser.add_argument("--source-font", default="train/FZNewKai.ttf")
    parser.add_argument("--charset", default="gb2312")
    parser.add_argument("--output-root", default="run/export_all_generated_fonts")
    parser.add_argument(
        "--style-folders",
        nargs="*",
        default=None,
        help="Optional subset of style folders. Accepts either full folder names like 005_九成宫 or suffix names like 九成宫.",
    )
    parser.add_argument("--family-prefix", default="Zi2ZiJIT")
    parser.add_argument("--style-name", default="Regular")
    parser.add_argument("--font-version", default="1.000")
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--cfg", type=float, default=None)
    parser.add_argument("--sampling-method", default=None)
    parser.add_argument("--num-sampling-steps", type=int, default=None)
    parser.add_argument("--device", default="cuda")
    parser.add_argument("--ref-index", type=int, default=0, choices=range(8))
    parser.add_argument("--reference-mode", choices=["fixed", "cycle"], default="fixed")
    parser.add_argument("--potrace-bin", default="potrace")
    parser.add_argument("--fontforge-bin", default="fontforge")
    parser.add_argument("--potrace-turdsize", type=int, default=2)
    parser.add_argument("--potrace-alphamax", type=float, default=1.0)
    parser.add_argument("--potrace-opttolerance", type=float, default=0.2)
    parser.add_argument("--keep-ungenerated-cjk", action="store_true")
    parser.add_argument("--strict", action="store_true")
    parser.add_argument("--keep-temp", action="store_true")
    parser.add_argument("--continue-on-error", action="store_true")
    parser.add_argument("--overwrite", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    return parser.parse_args()


def resolve_path(path_text: str) -> Path:
    path = Path(path_text)
    if not path.is_absolute():
        path = (REPO_ROOT / path).resolve()
    return path


def canonical_style_key(path: Path) -> str:
    return path.name.split("_", 1)[-1]


def sanitize_filename(text: str) -> str:
    text = text.strip()
    if not text:
        return "generated-font"
    text = re.sub(r'[<>:"/\\\\|?*]+', "_", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


def match_requested_styles(train_dir: Path, requested: list[str] | None) -> list[Path]:
    style_folders = sorted(
        path for path in train_dir.iterdir()
        if path.is_dir() and not path.name.startswith(".")
    )
    if not requested:
        if not style_folders:
            raise FileNotFoundError(f"No style folders found under {train_dir}")
        return style_folders

    by_full = {path.name: path for path in style_folders}
    grouped_by_suffix: dict[str, list[Path]] = {}
    for path in style_folders:
        grouped_by_suffix.setdefault(canonical_style_key(path), []).append(path)

    matched: list[Path] = []
    seen = set()
    for item in requested:
        if item in by_full:
            path = by_full[item]
        else:
            candidates = grouped_by_suffix.get(item, [])
            if not candidates:
                raise FileNotFoundError(
                    f"Could not find style folder '{item}' under {train_dir}. "
                    "Pass either the exact folder name or an unambiguous suffix name."
                )
            if len(candidates) > 1:
                names = ", ".join(path.name for path in candidates)
                raise RuntimeError(
                    f"Style name '{item}' matches multiple folders: {names}. "
                    "Pass the full folder name instead."
                )
            path = candidates[0]

        if path.name not in seen:
            matched.append(path)
            seen.add(path.name)

    return matched


def build_family_name(prefix: str, style_folder: Path) -> str:
    suffix = canonical_style_key(style_folder)
    if prefix:
        return f"{prefix} {suffix}".strip()
    return suffix or style_folder.name


def run(cmd: list[str], *, cwd: Path, dry_run: bool) -> None:
    print()
    print(" ".join(str(part) for part in cmd))
    if dry_run:
        return
    subprocess.run(cmd, check=True, cwd=cwd)


def main() -> None:
    args = parse_args()
    checkpoint = resolve_path(args.checkpoint)
    train_dir = resolve_path(args.train_dir)
    source_font = resolve_path(args.source_font)
    output_root = resolve_path(args.output_root)

    if not train_dir.is_dir():
        raise FileNotFoundError(f"Train dir not found: {train_dir}")
    if not source_font.is_file():
        raise FileNotFoundError(f"Source font not found: {source_font}")
    if not args.dry_run and not checkpoint.is_file():
        raise FileNotFoundError(f"Checkpoint not found: {checkpoint}")

    style_folders = match_requested_styles(train_dir, args.style_folders)
    generated_root = output_root / "generated"
    fonts_root = output_root / "fonts"
    reports_root = output_root / "reports"
    summary_path = output_root / "summary.json"

    summary: list[dict] = []
    failures: list[dict] = []

    print("Batch export plan:")
    print(f"  checkpoint        = {checkpoint}")
    print(f"  train_dir         = {train_dir}")
    print(f"  source_font       = {source_font}")
    print(f"  style_count       = {len(style_folders)}")
    print(f"  output_root       = {output_root}")
    print(f"  reference_mode    = {args.reference_mode}")
    print(f"  ref_index         = {args.ref_index}")
    print(f"  clear_template_cjk = {not args.keep_ungenerated_cjk}")

    for style_folder in style_folders:
        style_name = style_folder.name
        family_name = build_family_name(args.family_prefix, style_folder)
        safe_file_stem = sanitize_filename(style_name)
        style_generated_dir = generated_root / style_name
        style_font_path = fonts_root / f"{safe_file_stem}.ttf"
        generation_report = reports_root / style_name / "generation_manifest.json"
        font_report = reports_root / style_name / "font_build_report.json"

        record = {
            "style_folder": style_name,
            "generated_dir": str(style_generated_dir),
            "output_font": str(style_font_path),
            "family_name": family_name,
            "style_name": args.style_name,
        }

        if style_font_path.exists() and not args.overwrite:
            print()
            print(f"[skip] {style_name}: output font already exists at {style_font_path}")
            record["status"] = "skipped_existing"
            summary.append(record)
            continue

        generation_cmd = [
            sys.executable,
            str(REPO_ROOT / "scripts" / "generate_gb2312_from_finetune.py"),
            "--checkpoint", str(checkpoint),
            "--train-dir", str(train_dir),
            "--source-font", str(source_font),
            "--style-folder", style_name,
            "--charset", args.charset,
            "--output-dir", str(style_generated_dir),
            "--batch-size", str(args.batch_size),
            "--device", args.device,
            "--ref-index", str(args.ref_index),
            "--reference-mode", args.reference_mode,
        ]
        if args.cfg is not None:
            generation_cmd.extend(["--cfg", str(args.cfg)])
        if args.sampling_method is not None:
            generation_cmd.extend(["--sampling-method", args.sampling_method])
        if args.num_sampling_steps is not None:
            generation_cmd.extend(["--num-sampling-steps", str(args.num_sampling_steps)])
        if args.dry_run:
            generation_cmd.append("--dry-run")

        font_cmd = [
            sys.executable,
            str(REPO_ROOT / "scripts" / "build_font_with_fontforge.py"),
            "--generated-root", str(style_generated_dir),
            "--template-font", str(source_font),
            "--output-font", str(style_font_path),
            "--family-name", family_name,
            "--style-name", args.style_name,
            "--font-version", args.font_version,
            "--potrace-bin", args.potrace_bin,
            "--fontforge-bin", args.fontforge_bin,
            "--potrace-turdsize", str(args.potrace_turdsize),
            "--potrace-alphamax", str(args.potrace_alphamax),
            "--potrace-opttolerance", str(args.potrace_opttolerance),
            "--report-json", str(font_report),
        ]
        if args.keep_ungenerated_cjk:
            font_cmd.append("--keep-ungenerated-cjk")
        if args.strict:
            font_cmd.append("--strict")
        if args.keep_temp:
            font_cmd.append("--keep-temp")
        if args.dry_run:
            font_cmd.append("--dry-run")

        print()
        print(f"=== [{style_name}] generating GB2312 images ===")
        try:
            run(generation_cmd, cwd=REPO_ROOT, dry_run=args.dry_run)
            if not args.dry_run:
                manifest_path = style_generated_dir / "_gb2312_manifest.json"
                if manifest_path.is_file():
                    generation_report.parent.mkdir(parents=True, exist_ok=True)
                    generation_report.write_text(manifest_path.read_text(encoding="utf-8"), encoding="utf-8")

            print(f"=== [{style_name}] building font via potrace + FontForge ===")
            run(font_cmd, cwd=REPO_ROOT, dry_run=args.dry_run)
            record["status"] = "dry_run" if args.dry_run else "ok"
            summary.append(record)
        except subprocess.CalledProcessError as exc:
            record["status"] = "failed"
            record["returncode"] = exc.returncode
            failures.append(record)
            summary.append(record)
            if not args.continue_on_error:
                break
        except Exception as exc:  # pragma: no cover - defensive around external tools
            record["status"] = "failed"
            record["error"] = str(exc)
            failures.append(record)
            summary.append(record)
            if not args.continue_on_error:
                break

    output_root.mkdir(parents=True, exist_ok=True)
    with open(summary_path, "w", encoding="utf-8") as f:
        json.dump(
            {
                "checkpoint": str(checkpoint),
                "train_dir": str(train_dir),
                "source_font": str(source_font),
                "output_root": str(output_root),
                "style_count": len(style_folders),
                "success_count": sum(1 for item in summary if item["status"] in {"ok", "dry_run", "skipped_existing"}),
                "failure_count": len(failures),
                "items": summary,
            },
            f,
            ensure_ascii=False,
            indent=2,
        )

    print()
    print("Batch export complete.")
    print(f"  summary      = {summary_path}")
    print(f"  success      = {sum(1 for item in summary if item['status'] in {'ok', 'dry_run', 'skipped_existing'})}")
    print(f"  failed       = {len(failures)}")
    print(f"  fonts_root   = {fonts_root}")
    if failures:
        failed_names = ", ".join(item["style_folder"] for item in failures)
        raise SystemExit(f"Some styles failed: {failed_names}")


if __name__ == "__main__":
    main()
